<div class="container-fluid mywhite">
	<div class="row-fluid">
		<div class="span12 ">
		<div class="alert alert-success top-20">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <i class="icon-ok"></i> A Ocorrência Nº<?=$this->id?> foi criada com sucesso.
            </div>
		    <?php if (count($this->records) > 0):?>
		    <h3><i class="icon-file-alt"></i> Lista de Ocorrências de <?=$this->today?></h3>
			<table class="table table-striped txtsmall sp-bottom-30">
				<tr>
					<th><i class="icon-list-alt"></i> Nº</th>
					<th><i class="icon-user"></i> Entidade</th>
					<th><i class="icon-cog"></i> Sistema</th>
					<th><i class="icon-share"></i> Origem</th>
					<th><i class="icon-laptop"></i> Obra</th>
					<th><i class="icon-picture"></i> Produto</th>
					<th><i class="icon-pencil"></i> Editar</th>
					<th><i class="icon-cloud"></i> PDF</th>
				</tr>
			    <?php foreach ($this->records as $boletim):?>
			    
			    <tr>
					<td><a href="/view/<?=$boletim['id']?>"><i class="icon-eye-open"></i></a>&nbsp;&nbsp;<?=$boletim['id']?></td>
					<td><?=$boletim['entidade']?></td>
					<td><?=$boletim['sistema']?></td>
					<td><?=$boletim['origem']?></td>
					<td><?=RPS_Helpers_Transform_ZeroJob::remove($boletim['obra']);?></td>
					<td><?=RPS_Helpers_Transform_ShortText::reduce($boletim['trabalho'],35);?></td>
					<td><button class="btn btn-mini btn-warning">Editar</button></td>
					<td>
    					<div class="btn-group">
                          <a class="btn btn-mini btn-info dropdown-toggle" data-toggle="dropdown" href="#">
                            Criar PDF
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li><a href="/export/pdf/id/<?=$boletim['id']?>/t/interno" target="_blank">Interno</a></li>
                            <li class="dropdown-submenu">
                                <a tabindex="-1" href="#">Externo</a>
                                <ul class="dropdown-menu">
                                  <li><a href="/export/pdf/id/<?=$boletim['id']?>/u/carina/t/externo" target="_blank">Carina Santos</a></li>
                                  <li><a href="/export/pdf/id/<?=$boletim['id']?>/u/ana/t/externo" target="_blank">Ana Spinola</a></li>
                                  <li><a href="/export/pdf/id/<?=$boletim['id']?>/u/marta/t/externo" target="_blank">Marta Cabral</a></li>
                                  <li><a href="/export/pdf/id/<?=$boletim['id']?>/u/ines/t/externo" target="_blank">Ines Cardoso</a></li>
                                  <li><a href="/export/pdf/id/<?=$boletim['id']?>/u/margarida/t/externo" target="_blank">Margarida Salvado</a></li>
                                </ul>
                          </ul>
                        </div>
					</td>
				</tr>
			    <?php endforeach;?>
			</table>
			
	        <?php endif;?>
		</div>
	</div>
</div>