<div class="modal" id="datesmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel"><i class="icon-search"></i> Procurar por Datas</h3>
	</div>
	<div class="modal-body sp-bottom-10">
	    <div id="datesmodal-errors-form"></div>
	    <form action="/search/date" method="post" onsubmit="return validateDatesSearch()">
	        <table>
	        <tr>
	            <td><input type="text" id="dates-modal-search1" name="dates-modal-search1" placeholder="Escreva a data"/></td>
	            <td><input type="text" id="dates-modal-search2" name="dates-modal-search2" placeholder="Escreva a data"/></td>
	        </tr>
	        <tr>
	            <td><input type="submit" value="Procurar" class="btn btn-primary" /></td>
	        </tr>
	        </table>
	   </form>
	    
	    
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
	</div>
</div>