<div class="modal" id="numeromodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel"><i class="icon-search"></i> Procurar por Nº de Ocorrência</h3>
	</div>
	<div class="modal-body sp-bottom-10">
	    <div id="numero-modal-errors-form"></div>
	    <form action="/search/id" method="post" onsubmit="return validateNumberSearch()">
	        <table>
	        <tr>
	            <td><input type="text" id="numero-modal-search" name="numero-modal-search" placeholder="Escreva o número da ocorrência"/></td>
	        </tr>
	        <tr>
	            <td><input type="submit" value="Procurar" class="btn btn-primary" /></td>
	        </tr>
	        </table>
	   </form>
	    
	    
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
	</div>
</div>