<?php if ($this->errors):?>


<?php else:?>


 <div class="container-fluid "> 
        <div class="row-fluid"> 
           <div class="span7">
           
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <i class="icon-ok"></i> A Ocorrência Nº<?=$this->id?> foi actualizada com sucesso.
            </div>
           
           
                    
           <ul class="thumbnails">
				<li class="span4">
					<div class="thumbnail mywhite spacer10">
						<i class="icon-cloud-download icon-5x icon-edit-thumb"></i>
						<hr />
						<h3 class="text-center">Criar PDF</h3>
						<p class="txt-edit">Utilize esta opção para fazer um PDF.</p><br />
						<div class="centerz">
							<a href="/export/pdf/id/<?=$this->id;?>/t/interno"
								class="btn btn-primary left-30 sp-bottom-10" type="button" target="_blank">Criar PDF</a>
						</div>
					</div>
				</li>
				<li class="span4">
					<div class="thumbnail mywhite spacer10">
						<i class="icon-edit icon-5x icon-edit-thumb"></i>
						<hr />
						<h3 class="text-center">Editar</h3>
						<p class="txt-edit">Utilize esta opção para editar.</p><br /><br />
						<div class="centerz">
							<a href="/edit/" class="btn btn-primary left-30 sp-bottom-10" type="button">Editar</a>
						</div>
					</div>
				</li>
				<li class="span4">
					<div class="thumbnail mywhite spacer10">
						<i class="icon-list-alt icon-5x icon-edit-thumb"></i>
						<hr />
						<h3 class="text-center">Nova</h3>
						<p class="txt-edit">Utilize esta opção para criar uma nova Ocorrência.</p><br />
						<div class="centerz">
							<a href="/" class="btn btn-primary left-30 sp-bottom-10" type="button">Nova</a>
						</div>
					</div>
				</li>
			</ul>
           
           
           
           
           </div>
         </div>   
</div>









<?php endif;?>